services:
  database:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: mssql
    ports:
      - "1436:1433"
    environment:
      SA_PASSWORD: "YourStrong!Password"
      ACCEPT_EULA: "Y"
    volumes:
      - db_data:/var/opt/mssql

  backend:
    build:
      context: ./be
      dockerfile: Dockerfile
    ports:
      - "3006:3000"
    env_file:
      - ./be/.env
    depends_on:
      - database

  frontend:
    build:
      context: ./fe
      dockerfile: Dockerfile
    ports:
      - "8088:80"
    depends_on:
      - backend

volumes:
  db_data: