services:
  backend:
    build:
      context: ./be
      dockerfile: Dockerfile
    ports:
      - "${BACKEND_PORT:-36363}:3000"
    env_file:
      - ./be/.env
    volumes:
      - ./be/uploads:/usr/src/app/uploads

  frontend:
    build:
      context: ./fe
      dockerfile: Dockerfile
    ports:
      - "${FRONTEND_PORT:-34321}:80"
    depends_on:
      - backend

volumes:
  db_data: